[package]
name = "plug-and-hack"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.25", features = ["json"]}
tokio = {version = "1", features = ["full"]}
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
urlencoding = "2.1.3"